GET http://localhost:8000/kpis
Authorization: Basic c21hcnRhcHA6YXBp

###

GET http://localhost:8000/raw_data
Authorization: Basic c21hcnRhcHA6YXBp

###

GET http://localhost:8000/units
Authorization: Basic c21hcnRhcHA6YXBp

###

POST http://localhost:8000/add_kpi
Authorization: Basic c21hcnRhcHA6YXBp

{
  "name": "kpi bella",
  "description": "una kpi bellissima",
  "taxonomy": "non so cosa sia ancora",
  "kpi_range": "1-17",
  "formula": "3 + 4",
  "kpis": [
    "KPI1",
    "KPI2"
  ],
  "raw_data": [
    "rawdata2",
    "rawdata3"
  ],
  "unit": "ms/s",
  "frequency": "1 hour"
}